#!/bin/bash

if [ "$EUID" != "0" ]; then
  echo "You must be root to run this script. Sorry, dude!"
  exit 1
fi

LXCDIR="/var/lib/lxc"
CONFIG="config"
BASEDIR="baseFrr"

# Setup LXC and base container
apt-get -y --force-yes install lxc
mkdir -p $LXCDIR
lxc-create -t ubuntu -n $BASEDIR || exit 1

cp -f /etc/resolv.conf $LXCDIR/$BASEDIR/rootfs/etc
cp frr_3.0.2-1-ubuntu14.04.1_amd64.deb $LXCDIR/$BASEDIR/rootfs/home/ubuntu/


chroot $LXCDIR/$BASEDIR/rootfs apt-get update
# !!!
# ADD THE PACKETS YOU NEED TO INSTALL HERE
# !!!
chroot $LXCDIR/$BASEDIR/rootfs apt-get -y --force-yes install \
    libboost-thread-dev libboost-system-dev libboost-filesystem-dev \
    libboost-program-options-dev libnl-3-dev libnl-route-3-dev \
    rsyslog vlan tcpdump telnet iperf libc-ares2
chroot $LXCDIR/$BASEDIR/rootfs dpkg -i /home/ubuntu/frr_3.0.2-1-ubuntu14.04.1_amd64.deb
chroot $LXCDIR/$BASEDIR/rootfs apt-get install -f


# !!!

if [ -e /usr/local/lib/libzmq.so ]; then
    cp /usr/local/lib/libzmq.so $LXCDIR/$BASEDIR/rootfs/usr/lib
    chroot $LXCDIR/$BASEDIR/rootfs ldconfig
fi

# Clone the base container to make other containers based on config
cd $CONFIG
for VM in rfrrvmA rfrrvmB rfrrvmC rfrrvmD
do
    lxc-clone -o $BASEDIR -n $VM
    cp -R $VM/* $LXCDIR/$VM
done
